### ISSUE TITLE
streamsx.ngrams merge to streamsx.text toolkit

### ISSUE THREAD

**Issue by hleuschner** [IBMStreams/streamsx.text#3]
@leongor:
Hi Leonid,
please, merge streamsx.ngrams to streamsx.text toolkit as agreed in 
https://github.com/IBMStreams/administration/issues/96. 

The remaining steps are:

a) Rename
com.ibm.streamsx.ngrams::Ngrams
to
com.ibm.streamsx.text::Ngrams

b) Create a sample application to demonstrate the usage of the Ngrams operator (similar to existing sample https://github.com/IBMStreams/streamsx.text/tree/master/samples/NgramBasicSample).

c) After the merge, the streamsx.ngrams repository should be set to deprecated and should give a hint and link to the new location.

**Comment by leongor** [comment]
Created a pull request.

**Comment by markheger** [comment]
- Toolkit version changed to 1.1.0
- SPLDOC in gh-pages branch updated
- test case created for NgramSample project
- NgramSample depends on toolkit 1.1.0
